version: '3'

services:

  mongo:
    container_name: mongo
    image: mongo:4.0
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  app:
    container_name: app
    image: node:9
    hostname: myapp
    environment:
      WAIT_HOSTS: mongo:27017
    restart: always
    volumes: 
      - ./:/home/app
    working_dir: /home/app
    depends_on: 
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    # entrypoint: ["./wait-for-it.sh", "mongo:27017", "--strict", "--timeout=0", "npm", "run", "dev"]
    command: npm run dev